@startuml ControllerModel
    title Controller model
    class Command{
        + <<Property>>CommandComponent: string
        + <<Property>>Parameters: string[]
        + command(string): Command
    }
    note bottom: Parses user input as string in constructor

    interface IController{
        handle(Command)
    }

    abstract class AbstractController{
        
    }

    IController -left- Command: uses >

    class ChangeColourController implements IController{
        handle(Command)
    }
    
@enduml