@startuml ControllerModel
    title Controller model
    hide empty members
    class Command{
        + <<Property>>Keyword: string
        + <<Property>>Parameters: string[]
        + command(string): Command
    }
    note bottom: Parses user input as string in constructor

    interface IController{
        + handle(Command)
    }

    abstract class AbstractController implements IController{
        # GetAllowedCommandFormat(): Command
    }

    IController -left- Command: uses >

    class ChangeColourController extends AbstractController{
        + handle(Command)
    }
    
@enduml