@startuml Database

title Wardrobe database model
hide circle
hide methods

class Garment{
    id **PK**
    price
    brand_id //FK//
    size_id //FK//
}

class Size{
    id **PK**
    size_name
}

class Brand{
    id **PK**
    name
}

class Material{
    id **PK**
    colour_id //FK//
    name
}

class GarmentToMaterial{
    garment_id **PK** //FK//
    material_id **PK** //FK//
}

class Outfit{
    id **PK**
}

class Category{
    id **PK**
    name
}

class GarmentToOutfit{
    garment_id **PK** //FK//
    outfit_id **PK** //FK//
}

class Wear{
    date **PK**
    garment_id //FK//
}

class Colour{
    id **PK**
    colour_code
}


Garment "*" -- "1" Category
Garment "1" -- "1" GarmentToOutfit
GarmentToOutfit "1" -- "1" Outfit
Garment -- GarmentToMaterial
GarmentToMaterial -- Material
Garment -- Size
Garment "*" -- "1" Brand
Wear "*" -- "1" Garment
Material -- Colour


@enduml