@startuml Database

title Wardrobe database model
note as Info
This shows the intended structure of the 
backend database, though it was never
implemented
end note

object Garment{
    id **PK**
    price
    brand_id //FK//
    size_id //FK//
}

object GarmentToMaterial{
    garment_id **PK** //FK//
    material_id **PK** //FK//
}

object Outfit{
    id **PK**
}

object Category{
    id **PK**
    name
}

object GarmentToOutfit{
    garment_id **PK** //FK//
    outfit_id **PK** //FK//
}

object Size{
    id **PK**
    size_name
}

object Brand{
    id **PK**
    name
}

object Material{
    id **PK**
    colour_id //FK//
    name
}

object Wear{
    date **PK**
    garment_id //FK//
}

object Colour{
    id **PK**
    colour_code
}


Garment "1..*" -- "0..*" Outfit
(Garment, Outfit) .. GarmentToOutfit
Garment "0..*" -- "1..*" Material
(Garment, Material) .. GarmentToMaterial
Garment "*" -right- "1" Category
Garment -right- Size
Garment "*" -right- "1" Brand
Wear "*" -- "1" Garment
Material -- Colour

@enduml