@startuml GarmentFactory

'!include GarmentModel.puml!0
title Garment Factory model
hide empty members

remove Shade
remove Colour

skinparam groupInheritance 2

abstract GarmentFactory{
    + {abstract} CreateGarment(GarmentID)
}

class ShoeFactory extends GarmentFactory{
    + CreateGarment(): Shoe
}
class TopFactory extends GarmentFactory{
    + CreateGarment(): Top
}
class BottomFactory extends GarmentFactory{
    + CreateGarment(): Bottom
}
class AccessoryFactory extends GarmentFactory{
    + CreateGarment(): Accessory
}
class OuterwearFactory extends GarmentFactory{
    + CreateGarment(): Outerwear
}

@enduml