@startuml

skinparam groupInheritance 2

abstract GarmentFactory{
    + {abstract} CreateGarment(GarmentID)
}

class ShoeFactory extends GarmentFactory{
    + CreateGarment(): Garment
}

interface Garment{
    + name
    + type
    + price
}

class Shoe implements Garment
class Top implements Garment
class Pants implements Garment
GarmentFactory -- Garment

@enduml