@startuml MainProgramModel
    '!include DatabaseObjectModel.puml!0

    hide empty members    

    class WardrobeApplication{
        - Application
        + main()
    }

    class Application{
        Commands: Map<string, IController>
        + addController(string, IController)
        + runApplication()
    }

    class AppSettings{
        /' showColorNames()
        darkMode()
        lightMode() '/
    }

    Main o-- Application  

@enduml