!include DatabaseObjectModel.puml!0
@startuml

    hide empty members
    page 2x2
    skinparam pageMargin 10
    skinparam pageExternalColor gray
    skinparam pageBorderColor black
    

    class Program{
        commandMappings: Map<string, IController>
        + main()
    }

    class AppSettings{
        showColorNames()
        darkMode()
        lightMode()
    }

    /' Klasse som konverterer en string til en command og parameter '/
    class Command{
        commandComponent: string
        parameters: string[]
    }
    note bottom: Parses user input as string in constructor

    interface IController{
        handle(Command)
    }

    class ChangeColourController implements IController{
        handle(Command)
    }
    
    together {
        /'Objects returned from database'/
        class Garment{
            name: string
            price: double
            size: string
            category: string
            brand: string
            seasons: string[]
            materials: Material[]
            notes
        }

        class Material{
            colour
            fabric
        }
    }
    

    Garment o-- Material: Aggregation
    

@enduml